pipeline {
  agent {
    kubernetes {
      label "jenkins-pod-agent"
      defaultContainer("jnlp")
      yamlFile 'ci/pod.yaml'
    }
  }
  stages {
    stage('Check') {
      steps {
        container('node') {
          sh 'npm version'
        }
      }
    }
    stage('Build') {
      steps {
        container('node') {
          sh 'npm install'
        }
      }
    }

    stage('Publish') {
      steps {
        withCredentials([string(credentialsId: 'npm-access', variable: 'npmauth')]) {
            container('node') {
                sh '''
                    set +x
                    echo $npmauth > .npmrc
                   '''
                sh "cat .npmrc"
                sh 'npm version minor'
                sh 'npm publish --registry http://35.197.217.72:8081/repository/npm-private'
            }
        }
      }
    }
  }

  post {
    always {
        cleanWs()
    }
  }
}