pipeline {
  agent {
    kubernetes {
      label "jenkins-pod-agent"
      defaultContainer("jnlp")
      yamlFile 'ci/pod.yaml'
    }
  }
  stages {
    stage('Check') {
      steps {
        container('node') {
          sh 'npm version'
        }
      }
    }
    stage('Build') {
      steps {
        container('node') {
          sh 'npm install'
        }
      }
    }

    stage('Publish') {
      steps {
        withCredentials([file(credentialsId: 'npm-access-file', variable: 'npmauth'),
        usernamePassword(credentialsId: 'nexus-credentials', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
            container('node') {
                sh '''
                    cat $npmauth > .npmrc 
                    npm install -g npm-cli-login
                    npm-cli-login -u $USERNAME -p $PASSWORD -e admin@example.org -r http://35.197.217.72:8081/repository/npm-private/
                   '''
                sh 'npm version minor'
                sh 'npm publish --registry http://35.197.217.72:8081/repository/npm-private'
            }
        }
      }
    }
  }

  post {
    always {
        cleanWs()
    }
  }
}