apiVersion: v1
kind: Pod
metadata:
  generateName: jenkins-pod-agent
  labels:
    some-label: some-label-value
spec:
  containers:
  - name: node
    image: node:20.5-buster-slim
    command:
    - apt update && apt install -y git && cat
    tty: true

